wandb_version: 1

device:
  desc: null
  value: cuda
hidden_dim_critic:
  desc: null
  value: 256
hidden_dim_policy:
  desc: null
  value: 128
batch_size:
  desc: null
  value: 256
action_range:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.0003
discount:
  desc: null
  value: 0.97
gradient_steps:
  desc: null
  value: 4
reset_frequency:
  desc: null
  value: 2000
delta_entropy:
  desc: null
  value: 25
load_pretrained_models:
  desc: null
  value: false
max_iterations:
  desc: null
  value: 10000
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727986834.161965
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.9
      5: 0.15.8
      8:
      - 5
